### ISSUE TITLE
Typedoc is not avalible

### ISSUE THREAD

**Issue by DonsWayo** [Pop-Code/nestjs-mongo#55]
Hi, I want to try the library, but the typedoc shows a 404. Please , can you update or upload the typedoc somewhere?.

Thanks!!

**Comment by Rmannn** [comment]
Hi, 
I will publish the typedoc, I will release a first version in the next weeks with more documentation.
Actually the doc is very poor.
If you need to update the typedoc documentation (folder docs) on your side, after cloning this repo,  you can do it running a script => npm run doc or yarn run doc.

**Comment by Rmannn** [comment]
Typedoc has been published
